name: letropolis
description: Aplicación educativa para aprendizaje de palabras con IA

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # AWS
  amplify_flutter: ^1.4.1
  amplify_auth_cognito: ^1.4.1
  amplify_storage_s3: ^1.4.1

  # Camera
  camera: ^0.10.5+4
  image_picker: ^1.0.4

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  # Audio
  just_audio: ^0.9.35

  # Utils
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1

  # HTTP
  http: ^1.1.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true
